# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TableViewDemo
	pod 'Masonry'
	pod 'YYKit'
	pod 'UITableView+FDTemplateLayoutCell'
	pod 'SDWebImage'
	pod 'AFNetworking', '~>3.2.1'
	pod 'DZNEmptyDataSet'

  target 'TableViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
